[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_BASEURL = "https://ngyongkad.netlify.app/"
  HUGO_VERSION = "0.77.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.77.0" # if older, use format: 0.53 (no trailing zero)

[context.deploy-preview.environment]
  HUGO_VERSION = "0.77.0" 